<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>bb_joy</name>
  <version>0.1.0</version>
  <description>Xbox / PS5 手把透過 MAVROS 遙控 USV (ArduPilot) 的 ROS2 teleop 節點。</description>

  <maintainer email="danielhuang2735@gmail.com">JetSeaAI</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>mavros_msgs</exec_depend>
  <exec_depend>joy_linux</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
